backend:
  name: git-gateway
  branch: main

media_folder: "public/experiment/images"
public_folder: "/experiment/images"

collections:
  - name: "aim"
    label: "Aim"
    folder: "src/experiment"
    create: true
    slug: "aim"
    fields: 
      - { name: title, label: Title, widget: string, readOnly: true, default: "Aim" }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }
  
  - name: "contributors"
    label: "Contributors"
    folder: "src/experiment"
    create: true
    slug: "contributors"
    fields: 
      - { name: title, label: Title, widget: string, readOnly: true, default: "Contributors" }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }